language: node_js
node_js:
  - "stable"
  - "10"
  - "11"
  - "12"

sudo: true
addons:
  chrome: stable

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run test

after_success:
  - npm run push-codacy-coverage
